# This file was generated by GoReleaser. DO NOT EDIT.
cask "correlux" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "ccbcccc42576918c389323556b784c47ae82c4951c3835d3527f03583b671443"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5122c74eb211487c19f0f72970aff8255542afd72732da60ed0ee1b6163bb217"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1b208ced8bb0886a46527ced9173ada2b5f05975a77cceaec833e764ec835a7e"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "343991c851b6c8c5cef10b50e357596e5c49c2ed23f2185a8f1d1c257b4d103f"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "correlux"
  desc "Fleet-first Kubernetes troubleshooting from your terminal"
  homepage "https://github.com/aronk11/correlux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "correlux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/correlux"]
    end
  end

  # No zap stanza required
end
