# This file was generated by GoReleaser. DO NOT EDIT.
cask "correlux" do
  version "0.15.0"

  on_macos do
    on_arm do
      sha256 "7da461186ac6f211ee9162096073ceaea60d990aad9346030c032917398a0c41"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f330fefd69e3c5a1ff99ea2cb51991396212166410a96ac2a7521cc0a510b4b"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "445a4154bce64d0337e063e19de83b4716122be733501e01ab04a2b49e9ea30d"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a62b9b6610b0efa245f2a5f3d1265692cc7c89bdf886a2c9458686abeb625b36"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "correlux"
  desc "Fleet-first Kubernetes troubleshooting from your terminal"
  homepage "https://github.com/aronk11/correlux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "correlux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/correlux"]
    end
  end

  # No zap stanza required
end
