# This file was generated by GoReleaser. DO NOT EDIT.
cask "correlux" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "13dca7bace9a9d53421372d036f8c684fb503fafb0f27f7f2374b7af36658d1a"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd9b74f553967ace261711f8e50e2adc634977edbe9b0709e8280e9a19eef3f0"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b9c451325852ae35ee0220500ed980e22d56e07aedc51d09973185c6e9c3f847"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4f57cb5276fcfc9751cfdbec83a1285b7cd9b97851c9ce083aedb9704169f5df"
      url "https://github.com/aronk11/correlux/releases/download/v#{version}/correlux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "correlux"
  desc "Fleet-first Kubernetes troubleshooting from your terminal"
  homepage "https://github.com/aronk11/correlux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "correlux"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/correlux"]
    end
  end

  # No zap stanza required
end
